# Configuration file for JuliaFormatter.jl
# For more information, see: https://domluna.github.io/JuliaFormatter.jl/stable/config/

always_for_in = true
for_in_replacement = "âˆˆ"
always_use_return = true
margin = 92
remove_extra_newlines = true
short_to_long_function_def = true
